#############################################################################
# Makefile for building: mysqlclient
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  mysqlclient.pro
# Template: app
# Command: /home/stephane/Qt/5.5/gcc_64/bin/qmake -o Makefile mysqlclient.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../Qt/5.5/gcc_64/include -I../../Qt/5.5/gcc_64/include/QtWidgets -I../../Qt/5.5/gcc_64/include/QtGui -I../../Qt/5.5/gcc_64/include/QtSql -I../../Qt/5.5/gcc_64/include/QtCore -I. -I../../Qt/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /home/stephane/Qt/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mysqlclient1.0.0
DISTDIR = /home/stephane/workspace_cpp/mysqlclient/.tmp/mysqlclient1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/stephane/Qt/5.5/gcc_64 -Wl,-rpath,/home/stephane/Qt/5.5/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/stephane/Qt/5.5/gcc_64/lib -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		UI/Session/EditSessionWindow.cpp \
		UI/Session/SessionWindow.cpp \
		UI/MainWindow.cpp moc_EditSessionWindow.cpp \
		moc_SessionWindow.cpp \
		moc_MainWindow.cpp
OBJECTS       = main.o \
		EditSessionWindow.o \
		SessionWindow.o \
		MainWindow.o \
		moc_EditSessionWindow.o \
		moc_SessionWindow.o \
		moc_MainWindow.o
DIST          = ../../Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/qt.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/resources.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/moc.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/uic.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		mysqlclient.pro UI/Session/EditSessionWindow.h \
		UI/Session/SessionWindow.h \
		UI/MainWindow.h main.cpp \
		UI/Session/EditSessionWindow.cpp \
		UI/Session/SessionWindow.cpp \
		UI/MainWindow.cpp
QMAKE_TARGET  = mysqlclient
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = mysqlclient


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mysqlclient.pro ../../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/qt.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/resources.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/moc.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/uic.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		mysqlclient.pro \
		/home/stephane/Qt/5.5/gcc_64/lib/libQt5Widgets.prl \
		/home/stephane/Qt/5.5/gcc_64/lib/libQt5Gui.prl \
		/home/stephane/Qt/5.5/gcc_64/lib/libQt5Sql.prl \
		/home/stephane/Qt/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile mysqlclient.pro
../../Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt/5.5/gcc_64/mkspecs/common/unix.conf:
../../Qt/5.5/gcc_64/mkspecs/common/linux.conf:
../../Qt/5.5/gcc_64/mkspecs/common/sanitize.conf:
../../Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt/5.5/gcc_64/mkspecs/common/g++-base.conf:
../../Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt/5.5/gcc_64/mkspecs/qconfig.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt/5.5/gcc_64/mkspecs/features/qt_config.prf:
../../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt/5.5/gcc_64/mkspecs/features/spec_post.prf:
../../Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.5/gcc_64/mkspecs/features/default_pre.prf:
../../Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt/5.5/gcc_64/mkspecs/features/default_post.prf:
../../Qt/5.5/gcc_64/mkspecs/features/warn_on.prf:
../../Qt/5.5/gcc_64/mkspecs/features/qt.prf:
../../Qt/5.5/gcc_64/mkspecs/features/resources.prf:
../../Qt/5.5/gcc_64/mkspecs/features/moc.prf:
../../Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.5/gcc_64/mkspecs/features/uic.prf:
../../Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.5/gcc_64/mkspecs/features/exceptions.prf:
../../Qt/5.5/gcc_64/mkspecs/features/yacc.prf:
../../Qt/5.5/gcc_64/mkspecs/features/lex.prf:
mysqlclient.pro:
/home/stephane/Qt/5.5/gcc_64/lib/libQt5Widgets.prl:
/home/stephane/Qt/5.5/gcc_64/lib/libQt5Gui.prl:
/home/stephane/Qt/5.5/gcc_64/lib/libQt5Sql.prl:
/home/stephane/Qt/5.5/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile mysqlclient.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents UI/Session/EditSessionWindow.h UI/Session/SessionWindow.h UI/MainWindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp UI/Session/EditSessionWindow.cpp UI/Session/SessionWindow.cpp UI/MainWindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_EditSessionWindow.cpp moc_SessionWindow.cpp moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_EditSessionWindow.cpp moc_SessionWindow.cpp moc_MainWindow.cpp
moc_EditSessionWindow.cpp: ../../Qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../../Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		../../Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qline.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt/5.5/gcc_64/include/QtGui/qimage.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QLineEdit \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlineedit.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qframe.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpen.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QPushButton \
		../../Qt/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Qt/5.5/gcc_64/include/QtGui/qicon.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QSpinBox \
		../../Qt/5.5/gcc_64/include/QtWidgets/qspinbox.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvalidator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregularexpression.h \
		UI/Session/EditSessionWindow.h
	/home/stephane/Qt/5.5/gcc_64/bin/moc $(DEFINES) -I/home/stephane/Qt/5.5/gcc_64/mkspecs/linux-g++ -I/home/stephane/workspace_cpp/mysqlclient -I/home/stephane/workspace_cpp/mysqlclient -I/home/stephane/Qt/5.5/gcc_64/include -I/home/stephane/Qt/5.5/gcc_64/include/QtWidgets -I/home/stephane/Qt/5.5/gcc_64/include/QtGui -I/home/stephane/Qt/5.5/gcc_64/include/QtSql -I/home/stephane/Qt/5.5/gcc_64/include/QtCore UI/Session/EditSessionWindow.h -o moc_EditSessionWindow.cpp

moc_SessionWindow.cpp: ../../Qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../../Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		../../Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qline.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt/5.5/gcc_64/include/QtGui/qimage.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QListView \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlistview.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qframe.h \
		../../Qt/5.5/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../Qt/5.5/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qstyleoption.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvalidator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregularexpression.h \
		../../Qt/5.5/gcc_64/include/QtGui/qicon.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qslider.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractslider.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qstyle.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qtabbar.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qrubberband.h \
		../../Qt/5.5/gcc_64/include/QtCore/QItemSelection \
		../../Qt/5.5/gcc_64/include/QtCore/QJsonArray \
		../../Qt/5.5/gcc_64/include/QtCore/qjsonarray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt/5.5/gcc_64/include/QtCore/QStringListModel \
		../../Qt/5.5/gcc_64/include/QtCore/qstringlistmodel.h \
		UI/Session/EditSessionWindow.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QLineEdit \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlineedit.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpen.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QPushButton \
		../../Qt/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QSpinBox \
		../../Qt/5.5/gcc_64/include/QtWidgets/qspinbox.h \
		UI/Session/SessionWindow.h
	/home/stephane/Qt/5.5/gcc_64/bin/moc $(DEFINES) -I/home/stephane/Qt/5.5/gcc_64/mkspecs/linux-g++ -I/home/stephane/workspace_cpp/mysqlclient -I/home/stephane/workspace_cpp/mysqlclient -I/home/stephane/Qt/5.5/gcc_64/include -I/home/stephane/Qt/5.5/gcc_64/include/QtWidgets -I/home/stephane/Qt/5.5/gcc_64/include/QtGui -I/home/stephane/Qt/5.5/gcc_64/include/QtSql -I/home/stephane/Qt/5.5/gcc_64/include/QtCore UI/Session/SessionWindow.h -o moc_SessionWindow.cpp

moc_MainWindow.cpp: UI/Session/EditSessionWindow.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../../Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		../../Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qline.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt/5.5/gcc_64/include/QtGui/qimage.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QLineEdit \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlineedit.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qframe.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpen.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QPushButton \
		../../Qt/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Qt/5.5/gcc_64/include/QtGui/qicon.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QSpinBox \
		../../Qt/5.5/gcc_64/include/QtWidgets/qspinbox.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvalidator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregularexpression.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QMainWindow \
		../../Qt/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Qt/5.5/gcc_64/include/QtCore/QDebug \
		UI/MainWindow.h
	/home/stephane/Qt/5.5/gcc_64/bin/moc $(DEFINES) -I/home/stephane/Qt/5.5/gcc_64/mkspecs/linux-g++ -I/home/stephane/workspace_cpp/mysqlclient -I/home/stephane/workspace_cpp/mysqlclient -I/home/stephane/Qt/5.5/gcc_64/include -I/home/stephane/Qt/5.5/gcc_64/include/QtWidgets -I/home/stephane/Qt/5.5/gcc_64/include/QtGui -I/home/stephane/Qt/5.5/gcc_64/include/QtSql -I/home/stephane/Qt/5.5/gcc_64/include/QtCore UI/MainWindow.h -o moc_MainWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt/5.5/gcc_64/include/QtWidgets/QApplication \
		../../Qt/5.5/gcc_64/include/QtWidgets/qapplication.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		../../Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qline.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt/5.5/gcc_64/include/QtGui/qimage.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		../../Qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		UI/MainWindow.h \
		UI/Session/EditSessionWindow.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../../Qt/5.5/gcc_64/include/QtWidgets/QLineEdit \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlineedit.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qframe.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpen.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QPushButton \
		../../Qt/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Qt/5.5/gcc_64/include/QtGui/qicon.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QSpinBox \
		../../Qt/5.5/gcc_64/include/QtWidgets/qspinbox.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvalidator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregularexpression.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QMainWindow \
		../../Qt/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Qt/5.5/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

EditSessionWindow.o: UI/Session/EditSessionWindow.cpp UI/Session/EditSessionWindow.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../../Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		../../Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qline.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt/5.5/gcc_64/include/QtGui/qimage.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QLineEdit \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlineedit.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qframe.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpen.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QPushButton \
		../../Qt/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Qt/5.5/gcc_64/include/QtGui/qicon.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QSpinBox \
		../../Qt/5.5/gcc_64/include/QtWidgets/qspinbox.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvalidator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregularexpression.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QFormLayout \
		../../Qt/5.5/gcc_64/include/QtWidgets/qformlayout.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QLayout \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlayout.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qboxlayout.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qgridlayout.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QHBoxLayout \
		../../Qt/5.5/gcc_64/include/QtWidgets/QVBoxLayout \
		../../Qt/5.5/gcc_64/include/QtGui/QIntValidator \
		../../Qt/5.5/gcc_64/include/QtCore/QString \
		../../Qt/5.5/gcc_64/include/QtCore/QDebug \
		../../Qt/5.5/gcc_64/include/QtSql/QSqlDatabase \
		../../Qt/5.5/gcc_64/include/QtSql/qsqldatabase.h \
		../../Qt/5.5/gcc_64/include/QtSql/qsql.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EditSessionWindow.o UI/Session/EditSessionWindow.cpp

SessionWindow.o: UI/Session/SessionWindow.cpp ../../Qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../../Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		../../Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qline.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt/5.5/gcc_64/include/QtGui/qimage.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QVBoxLayout \
		../../Qt/5.5/gcc_64/include/QtWidgets/qboxlayout.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlayout.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qgridlayout.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QPushButton \
		../../Qt/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Qt/5.5/gcc_64/include/QtGui/qicon.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QBoxLayout \
		../../Qt/5.5/gcc_64/include/QtWidgets/QMainWindow \
		../../Qt/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Qt/5.5/gcc_64/include/QtCore/QSettings \
		../../Qt/5.5/gcc_64/include/QtCore/qsettings.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QLabel \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlabel.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qframe.h \
		../../Qt/5.5/gcc_64/include/QtCore/QDebug \
		../../Qt/5.5/gcc_64/include/QtWidgets/QListView \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlistview.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../Qt/5.5/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../Qt/5.5/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qstyleoption.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvalidator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregularexpression.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qslider.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractslider.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qstyle.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qtabbar.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qrubberband.h \
		../../Qt/5.5/gcc_64/include/QtCore/QStringListModel \
		../../Qt/5.5/gcc_64/include/QtCore/qstringlistmodel.h \
		../../Qt/5.5/gcc_64/include/QtCore/QStringList \
		../../Qt/5.5/gcc_64/include/QtCore/QCoreApplication \
		../../Qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QMessageBox \
		../../Qt/5.5/gcc_64/include/QtWidgets/qmessagebox.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qdialog.h \
		../../Qt/5.5/gcc_64/include/QtCore/QJsonObject \
		../../Qt/5.5/gcc_64/include/QtCore/qjsonobject.h \
		../../Qt/5.5/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt/5.5/gcc_64/include/QtCore/QJsonValue \
		../../Qt/5.5/gcc_64/include/QtCore/QJsonDocument \
		../../Qt/5.5/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QShortcut \
		../../Qt/5.5/gcc_64/include/QtWidgets/qshortcut.h \
		UI/Session/SessionWindow.h \
		../../Qt/5.5/gcc_64/include/QtCore/QItemSelection \
		../../Qt/5.5/gcc_64/include/QtCore/QJsonArray \
		../../Qt/5.5/gcc_64/include/QtCore/qjsonarray.h \
		UI/Session/EditSessionWindow.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QLineEdit \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlineedit.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpen.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QSpinBox \
		../../Qt/5.5/gcc_64/include/QtWidgets/qspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SessionWindow.o UI/Session/SessionWindow.cpp

MainWindow.o: UI/MainWindow.cpp UI/MainWindow.h \
		UI/Session/EditSessionWindow.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../../Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		../../Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.5/gcc_64/include/QtCore/qline.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt/5.5/gcc_64/include/QtGui/qimage.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QLineEdit \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlineedit.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qframe.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextcursor.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextformat.h \
		../../Qt/5.5/gcc_64/include/QtGui/qpen.h \
		../../Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QPushButton \
		../../Qt/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Qt/5.5/gcc_64/include/QtGui/qicon.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QSpinBox \
		../../Qt/5.5/gcc_64/include/QtWidgets/qspinbox.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../Qt/5.5/gcc_64/include/QtGui/qvalidator.h \
		../../Qt/5.5/gcc_64/include/QtCore/qregularexpression.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QMainWindow \
		../../Qt/5.5/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Qt/5.5/gcc_64/include/QtCore/QDebug \
		../../Qt/5.5/gcc_64/include/QtCore/QSettings \
		../../Qt/5.5/gcc_64/include/QtCore/qsettings.h \
		UI/Session/SessionWindow.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/QListView \
		../../Qt/5.5/gcc_64/include/QtWidgets/qlistview.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../Qt/5.5/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../Qt/5.5/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qstyleoption.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qslider.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qabstractslider.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qstyle.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qtabbar.h \
		../../Qt/5.5/gcc_64/include/QtWidgets/qrubberband.h \
		../../Qt/5.5/gcc_64/include/QtCore/QItemSelection \
		../../Qt/5.5/gcc_64/include/QtCore/QJsonArray \
		../../Qt/5.5/gcc_64/include/QtCore/qjsonarray.h \
		../../Qt/5.5/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt/5.5/gcc_64/include/QtCore/QStringListModel \
		../../Qt/5.5/gcc_64/include/QtCore/qstringlistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o UI/MainWindow.cpp

moc_EditSessionWindow.o: moc_EditSessionWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EditSessionWindow.o moc_EditSessionWindow.cpp

moc_SessionWindow.o: moc_SessionWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SessionWindow.o moc_SessionWindow.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

