######################################################################
# Automatically generated by qmake (3.0) dim. f�vr. 28 19:12:57 2016
######################################################################

TEMPLATE = app
TARGET = mysqlclient
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += UI/Session/EditSessionWindow.h UI/Session/SessionWindow.h UI/MainWindow.h
SOURCES += main.cpp UI/Session/EditSessionWindow.cpp UI/Session/SessionWindow.cpp UI/MainWindow.cpp
