######################################################################
# Automatically generated by qmake (3.0) dim. f�vr. 28 19:12:57 2016
######################################################################

TEMPLATE = app
TARGET = mysqlclient
INCLUDEPATH += .
QT += widgets
QT += sql

# Input
HEADERS += UI/Session/EditSessionWindow.h UI/Session/SessionWindow.h UI/MainWindow.h UI/Explorer/Explorer.h UI/Explorer/DataBaseTree.h UI/Explorer/Model/DataBaseModel.h  UI/Explorer/Model/TableFilterProxyModel.h
SOURCES += main.cpp UI/Session/EditSessionWindow.cpp UI/Session/SessionWindow.cpp UI/MainWindow.cpp UI/Explorer/Explorer.cpp UI/Explorer/DataBaseTree.cpp UI/Explorer/Model/DataBaseModel.cpp UI/Explorer/Model/TableFilterProxyModel.cpp
