######################################################################
# Automatically generated by qmake (3.0) lun. mars 14 20:50:03 2016
######################################################################

CONFIG += qt debug
QT += widgets sql
TEMPLATE = app
TARGET = SmartSQL
INCLUDEPATH += .
DESTDIR = ../dist
RESOURCES     = mysqlclient.qrc

# Input
HEADERS += UI/MainWindow.h \
			UI/ToolBar.h \
			Util/DataBase.h \
           UI/Explorer/DataBaseTree.h \
           UI/Explorer/ServerAction/ShowProcessesWindow.h \
           UI/Explorer/Explorer.h \
           UI/Session/EditSessionWindow.h \
           UI/Session/SessionWindow.h \
           UI/Explorer/Model/DataBaseModel.h \
           UI/Explorer/Model/TableFilterProxyModel.h \
           UI/Explorer/Tabs/SQLSyntaxHighlighter.h \
           UI/Explorer/Tabs/Database/DataBaseTab.h \
           UI/Explorer/Tabs/Query/QueryModel.h \
           UI/Explorer/Tabs/Query/QueryTab.h \
           UI/Explorer/Tabs/Query/QueryThread.h \
           UI/Explorer/Tabs/Query/QueryTextEdit.h \
           UI/Explorer/Tabs/Table/TableFilterTextEdit.h \
           UI/Explorer/Tabs/Table/TableModel.h \
           UI/Explorer/Tabs/TabView.h \
           UI/Explorer/Tabs/TabBar.h \
           UI/Explorer/Tabs/Table/TableTab.h \
    UI/Explorer/ServerAction/NewDatabaseWindow.h \
    UI/Explorer/Tabs/TableDetails/TableDetailsModel.h \
    UI/Explorer/Tabs/Server/ServerTab.h \
    UI/Explorer/Tabs/Database/DatabaseModel.h \
    UI/Explorer/Export/ExportWindow.h \
    Util/MySQLDump.h \
    UI/Explorer/Tabs/Query/ResultTableView.h \
    UI/Explorer/Tabs/TableDetails/TableDetailsTab.h \
    UI/Explorer/Tabs/TableDetails/ForeignKeyModel.h \
    UI/Explorer/Tabs/TableDetails/TableIndexModel.h \
    Util/TableDefinition.h \
    UI/Explorer/Tabs/Table/InsertWindow.h
SOURCES += main.cpp \
		Util/DataBase.cpp \
           UI/MainWindow.cpp \
           UI/ToolBar.cpp \
           UI/Explorer/DataBaseTree.cpp \
           UI/Explorer/Explorer.cpp \
           UI/Explorer/ServerAction/ShowProcessesWindow.cpp \
           UI/Session/EditSessionWindow.cpp \
           UI/Session/SessionWindow.cpp \
           UI/Explorer/Model/DataBaseModel.cpp \
           UI/Explorer/Model/TableFilterProxyModel.cpp \
           UI/Explorer/Tabs/SQLSyntaxHighlighter.cpp \
           UI/Explorer/Tabs/TabView.cpp \
           UI/Explorer/Tabs/TabBar.cpp \
           UI/Explorer/Tabs/Database/DataBaseTab.cpp \
           UI/Explorer/Tabs/Query/QueryModel.cpp \
           UI/Explorer/Tabs/Query/QueryTab.cpp \
           UI/Explorer/Tabs/Query/QueryThread.cpp \
           UI/Explorer/Tabs/Query/QueryTextEdit.cpp \
           UI/Explorer/Tabs/Table/TableFilterTextEdit.cpp \
           UI/Explorer/Tabs/Table/TableModel.cpp \
           UI/Explorer/Tabs/Table/TableTab.cpp \
    UI/Explorer/ServerAction/NewDatabaseWindow.cpp \
    UI/Explorer/Tabs/TableDetails/TableDetailsModel.cpp \
    UI/Explorer/Tabs/Server/ServerTab.cpp \
    UI/Explorer/Tabs/Database/DatabaseModel.cpp \
    UI/Explorer/Export/ExportWindow.cpp \
    Util/MySQLDump.cpp \
    UI/Explorer/Tabs/Query/ResultTableView.cpp \
    UI/Explorer/Tabs/TableDetails/TableDetailsTab.cpp \
    UI/Explorer/Tabs/TableDetails/ForeignKeyModel.cpp \
    UI/Explorer/Tabs/TableDetails/TableIndexModel.cpp \
    Util/TableDefinition.cpp \
    UI/Explorer/Tabs/Table/InsertWindow.cpp
TRANSLATIONS += mysqlclient_en.ts

win32:debug {
    CONFIG += console
}

DISTFILES +=
